# need 4 gpus
# torchrun --nnodes 1 --nproc_per_node 8 run.py args/gsm_cot.yaml

project: coconut
save_path: /root/autodl-tmp/simcot_coconut/ckpts
name: gsm_cot

only_eval: False

coconut: False
cot: True
no_thoughts: False
no_cot: False
coconutgpt: True

c_thought: 0
epochs_per_stage: 1
max_latent_stage: 0
pad_latent_to_max: True

save_only_improve: True
uniform_prob: 0.0

# Model and checkpoint paths - use relative paths or environment variables
model_id: /root/autodl-tmp/hf_cache/hub/models--openai-community--gpt2/snapshots/607a30d783dfa663caf39e06633721c8d4cfcd7e
load_model_path: None   # no checkpoint for explicit CoT SFT
seed: 0
resume: 0
bf16: False

train_path: /root/autodl-tmp/simcot_coconut/data/gsm8k_aug_train.json
val_path: /root/autodl-tmp/simcot_coconut/data/gsm8k_aug_test.json

reset_optimizer: False
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 25
lr: !!float "1e-4"
weight_decay: 0.01

mode: coconut_baseline
training_method: only_base_causallm

wandb: False
